version: 2.1

jobs:
  build:
    docker:
     - image: cimg/node:20.15.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install

  test:
    docker:
     - image: cimg/node:20.15.1
    steps:
        - checkout
        - run: echo "testing stuff"
        - run: npm install
  
  hithere:
    docker:
     - image: cimg/node:20.15.1
    steps:
      - checkout
      - run: echo "helooo"

workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere